name: Build GhostSurf VST3

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clone JUCE
      run: git clone --depth=1 https://github.com/juce-framework/JUCE.git

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64

    - name: Build VST3
      run: cmake --build build --config Release

    - name: Install Inno Setup
      run: choco install innosetup --yes --no-progress

    - name: Build Installer EXE
      run: |
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
      shell: pwsh

    - name: Upload VST3 (dossier brut)
      uses: actions/upload-artifact@v4
      with:
        name: GhostSurf-VST3-Windows
        path: build/GhostSurf_artefacts/Release/VST3/GhostSurf.vst3
        retention-days: 30

    - name: Upload Installateur EXE
      uses: actions/upload-artifact@v4
      with:
        name: GhostSurf-Setup-EXE
        path: Output/GhostSurf_Setup.exe
        retention-days: 30
